### ISSUE TITLE
variables no necesarias

### ISSUE THREAD

**Issue by juanbono** [pdep-utn-frd/2020-mensajeros-LSFleitas#2]
Hola! Estas 2 variables no son necesarias porque el precio del paqueton viajero  se calcula en base a la cantidad de destinos que tenga.
https://github.com/pdep-utn-frd/2020-mensajeros-LSFleitas/blob/22eeb3d1b046a538ab1980cac4b8083099539bd6/src/mensajeros.wlk#L151-L152

**Comment by LSFleitas** [comment]
Claro, entiendo, pero lo hice de esa forma porque dice que el paquete puede ser "parcialmente pagado". Pero asumí que hasta que el paquete no pueda ser enviado, la mensajería no lo factura. Entonces, una de esas variables indica el valor total del paquete (el que factura la mensajeria), y el otro indica lo que resta pagar para que pueda ser enviado. Si no lo hacía de esa manera, iba a perder información acerca del valor del paquete.
Por ejemplo, si el paquete tiene 4 destinos, su valor total es 450. Pero si viene alguien y solo bonifica 200, restaría bonificar 250 para que pueda ser enviado. Pero el valor total del paquete sigue siendo 450, y mientras aún no se haya bonificado todo lo otro, la mensajería no puede enviar el paquete y por lo tanto no lo factura. Si yo no utilizo una variable para cada cosa, o bien no puedo pagar una parte del valor del paquete, o bien se me va a perder una parte del valor total del paquete, que es independiente de cómo se lo haya pagado.

**Comment by juanbono** [comment]
Claro, pero no es necesario guardar el `valor`. Porque lo podes saber en cualquier momento al fijarte la cantidad de destinos y multiplicarla por 100 (es decir, no es necesario guardarla si se puede calcular).
Otra cosa es que el paqueton viajero no tiene un precio inicial de 50. Sino de 0 (ya que no tiene destino cargado)

**Comment by LSFleitas** [comment]
Perfecto ya te entendí.
Lo del precio inicial entendí mal, pense que era del paqueton viajero, era del paquete. Ahora realizo las modificaciones.

**Comment by juanbono** [comment]
En el ultimo cambio que subiste hay un detalle, en el metodo `estaPago` debes devolver si el paquete esta pago o no (un booleano) pero no realizas ningun chequeo en ese metodo.
Por lo que deberias mover ahi la logica de chequear si ya esta totalmente pago.

Tambien podes aprovechar para simplificar algunos metodos:

Como la cantidad que debes pagar es siempre `destinos.size() * 100`, no es necesario que vayas sumando 100 cada vez que agregas un destino en:
```wollok
	method destino(unDestino) {
		destinos.add(unDestino)
		precio += 100
	}
```
Por lo que podes sacar esa suma y dejar solamente el `destinos.add(unDestino`.
Tambien este codigo
```wollok
		if ( precio > unaCantidad )
			precio -= unaCantidad
		else
			precio = 0
```
lo podes hacer mas sencillo (sin usar if) usando el metodo `max()` de la siguiente manera:
```wollok
precio = (precio - unaCantidad).max(0)
```
Asi: 
- si `(precio - unaCantidad)` es mayor que 0, el precio va a tomar el valor de `(precio - unaCantidad)`
- si `(precio - unaCantidad)` es menor que 0, el precio va a pasar a ser 0 debido a que `numNegativo.max(0)` es 0

**Comment by LSFleitas** [comment]
Hola Juan.
Corregí el metodo estaPago() de paqueton viajero.
Entendí y tomé la segunda sugerencia que me diste, así que ya mejoré esa parte.
Con respecto al primero, algo que no logro ver es esto:
Si quito esa línea, el precio del paqueton siempre va a ser cero. Y si pongo el precio directamente en función de la cantidad de destinos, no se va a poder pagar parte del precio total del paqueton.
No digo que no lo tengo que corregir, sino simplemente que no entiendo cómo es que seguiría funcionando, si me podes dar una mano para verlo con más claridad te agradecería jajaja.
Saludos!

**Comment by lspigariol** [comment]
listo, te arregle lo que decia juan y algo más. fijate.
