### ISSUE TITLE
Ademas de poder pasar por todos los destinos, tambien debe estar pago

### ISSUE THREAD

**Issue by juanbono** [pdep-utn-frd/2020-mensajeros-LSFleitas#3]
https://github.com/pdep-utn-frd/2020-mensajeros-LSFleitas/blob/22eeb3d1b046a538ab1980cac4b8083099539bd6/src/mensajeros.wlk#L179

**Comment by LSFleitas** [comment]
Lo que pasa es que yo asumí la siguiente idea:
Al paquete solo le interesa si puede ser ENTREGADO. El paquete verifica si puede ser ENTREGADO.
Quien envía los paquetes, es la MENSAJERIA. La mensajería es quien verifica si un paquete puede ser ENVIADO.
En la consigna, se especifican las condiciones para que el paquete sea ENTREGADO y las condiciones para que el paquete sea ENVIADO.
Basándome en eso es que el chequeo de que esté pago lo utilizo en la MENSAJERIA para verificar si el paquete puede ser ENVIADO.
En el caso del paquetonViajero, puede ser ENVIADO si está pago, y ENTREGADO si el mensajero puede pasar por todos los destinos (así, tal cual, está especificado en la consigna).
El control de las pruebas que tiene que pasar para ser ENTREGADO se las delegue al paquete; el control de las pruebas que tiene que pasar para ser ENVIADO se las delegué a la mensajeria.
Como el paquete **puede ser ENVIADO si el paquete esta pago (control que realiza la mensajería)** y además si este puede ser entregado por algún mensajero (control que realiza el paquete), en la mensajería, en el metodo enviarPaquete, es donde yo puse la parte de que sea enviado si está pago, que es lo que la consigna dice. Si el paquete no está pago, por más que pueda ser entregado, se va a la lista de Pendientes.

**Comment by juanbono** [comment]
Ahh entiendo, pero no fuiste consistente con esto en los 3 paquetes. Porque en el `paquete` chequeas 2 veces si esta pago, una vez en `estaEntregadoPor` y otra vez en el metodo para enviarlo

**Comment by LSFleitas** [comment]
Buenísimo, lo voy a modificar entonces. Le voy a delegar a la mensajería el control de todos los pagos. Igualmente me estaría saliendo un poco de la consigna original, pero es a fines de que quede de la misma manera para todos los paquetes. Gracias!
